[env:esp32s3-EBYTE-E22P-915M30S]
extends = esp32s3_base
board = esp32-s3-devkitc-1-n16r8v
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
monitor_filters = esp32_exception_decoder
build_flags = 
    ${esp32s3_base.build_flags} 
    -D PRIVATE_HW 
    -I variants/esp32s3/esp32s3_EBYTE_E22P_915M30S
lib_deps = 
    ${esp32s3_base.lib_deps}